name: CI/CD for Live Football Scores App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pip install pytest
          pytest tests/  # Assuming tests are located in the 'tests' folder

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        run: |
          echo "Deploying to Render..."
          curl -X POST -H "Authorization: Bearer ${{ secrets.FOOTIEFLASH }}" \
               -H "Content-Type: application/json" \
               -d '{"serviceId":"srv-ctg41b52ng1s73bc59e0"}' \
               https://api.render.com/v1/services/deploy
